name: ucs-model-review
channels:
    - conda-forge
dependencies:
    # Requirements for core model functionality
    - python==3.10.13
    - pip
    - ipython
    - matplotlib
    - pandas
    - geopandas
    - numpy
    - scipy
    - ipykernel
    - jupyterlab
    - seaborn
    - pypsa
    - plotly
    - pyarrow
    - pip:
      - gridstatus
      - highspy
      - nrelpy
      - us
      - census
